import { logAudit } from "../../lib/audit";
import { authenticate, database, prepareDatabase } from "../workspace/route";

const esc=(value:unknown)=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]||char));
const amount=(value:unknown,currency:unknown)=>new Intl.NumberFormat("en-US",{style:"currency",currency:String(currency||"RUB")}).format(Number(value||0));
const assetUrl=(request:Request,raw:unknown)=>{const src=String(raw??"").trim();if(!src)return "";if(src.startsWith("/"))return new URL(src,request.url).href;return new URL(`/api/template-assets?src=${encodeURIComponent(src)}`,request.url).href};
const richText=(value:unknown)=>esc(value).replace(/\n/g,"<br>");

export async function GET(request:Request){
  try{
    await prepareDatabase();const actor=await authenticate(request);
    const url=new URL(request.url);const id=Number(url.searchParams.get("id"));if(!id)throw new Error("Invoice is required");
    const invoice=await database().prepare(`SELECT i.*,c.name AS client_name,c.address AS client_address,c.email AS client_email,c.phone AS client_phone,c.contact_person AS client_contact,c.bank_account_number AS client_account,o.order_no,o.description AS order_description,b.nickname AS bank_nickname,b.bank_name AS receiving_bank,b.currency AS bank_currency,b.account_last4,t.name AS current_template_name,t.title AS current_title,t.header_text AS current_header_text,t.header_image_url AS current_header_image_url,t.seller_name AS current_seller_name,t.seller_address AS current_seller_address,t.seller_email AS current_seller_email,t.seller_phone AS current_seller_phone,t.tax_registration AS current_tax_registration,t.bank_details AS current_bank_details,t.payment_terms AS current_payment_terms,t.footer AS current_footer,t.footer_image_url AS current_footer_image_url,t.accent_color AS current_accent_color,t.custom_fields_json AS current_custom_fields FROM invoices i JOIN clients c ON c.id=i.client_id JOIN bank_accounts b ON b.id=i.bank_account_id LEFT JOIN orders o ON o.id=i.order_id LEFT JOIN invoice_templates t ON t.id=i.template_id WHERE i.id=?`).bind(id).first<Record<string,unknown>>();
    if(!invoice)return Response.json({error:"Invoice not found"},{status:404});
    const download=url.searchParams.get("download")==="1";
    await logAudit(actor.id,download?"downloaded":"viewed",download?"invoice":"invoice",id,`${actor.displayName} ${download?"downloaded":"viewed"} ${invoice.invoice_no}`,{invoiceNo:invoice.invoice_no,mode:download?"download":"view"});
    const items=(await database().prepare("SELECT * FROM invoice_items WHERE invoice_id=? ORDER BY id").bind(id).all()).results as Record<string,unknown>[];
    const lineRows=items.length?items.map(item=>`<tr><td>${esc(item.description||invoice.order_description)}</td><td>${esc(item.quantity||1)}</td><td>${amount(item.unit_price,invoice.currency)}</td><td>${amount(Number(item.quantity||0)*Number(item.unit_price||0),invoice.currency)}</td></tr>`).join(""):`<tr><td>${esc(invoice.order_description)}</td><td>1</td><td>${amount(invoice.subtotal,invoice.currency)}</td><td>${amount(invoice.subtotal,invoice.currency)}</td></tr>`;
    let snapshot:Record<string,unknown>={};try{snapshot=JSON.parse(String(invoice.template_snapshot||"{}")) as Record<string,unknown>}catch{/* keep safe invoice defaults */}
    const field=(snapshotKey:string,currentKey:string,fallback="")=>snapshot[snapshotKey]??invoice[currentKey]??fallback;
    let custom:Array<{label:string;value:string}>=[];try{custom=JSON.parse(String(field("custom_fields_json","current_custom_fields","[]")))}catch{/* ignore invalid legacy custom fields */}
    const accent=/^#[0-9a-f]{6}$/i.test(String(field("accent_color","current_accent_color")))?String(field("accent_color","current_accent_color")):"#176f8f";
    const headerText=String(field("header_text","current_header_text","")).trim();
    const headerImage=assetUrl(request,field("header_image_url","current_header_image_url",""));
    const footerImage=assetUrl(request,field("footer_image_url","current_footer_image_url",""));
    const logoSrc=headerImage||new URL("/stablecount-logo.png",request.url).href;
    const headerBlock=headerText?`<section class="doc-header-text">${richText(headerText)}</section>`:"";
    const footerBlock=[`<p class="footer">${richText(field("footer","current_footer","Thank you for your business"))}</p>`,footerImage?`<section class="doc-footer-image"><img src="${esc(footerImage)}" alt="Footer"/></section>`:""].join("");
    const html=`<!doctype html><html><head><meta charset="utf-8"><title>${esc(invoice.invoice_no)}</title><style>
      :root{--accent:${accent}}*{box-sizing:border-box}body{margin:0;background:#eef3f4;color:#173744;font:14px Arial,sans-serif}.sheet{width:min(900px,calc(100% - 32px));margin:28px auto;padding:48px;background:white;box-shadow:0 12px 36px #17374420}.doc-header-text{margin:0 0 18px;padding:14px 16px;border:1px solid #dce5e8;border-radius:10px;background:#f7fafb;color:#35515d;line-height:1.65;font-size:13px}.doc-footer-image{margin-top:18px;text-align:center}.doc-footer-image img{max-width:100%;max-height:120px;object-fit:contain}.top{display:flex;justify-content:space-between;gap:30px;border-bottom:4px solid var(--accent);padding-bottom:24px;margin-top:4px}.logo{width:235px;max-height:72px;object-fit:contain;object-position:left}.title{text-align:right}.title h1{margin:0;color:var(--accent);font-size:34px}.title b{display:block;margin-top:8px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:32px;margin:30px 0}.label{color:#6f838b;font-size:11px;font-weight:bold;text-transform:uppercase;letter-spacing:.08em}.address{white-space:pre-line;line-height:1.6}.meta{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin-top:14px}.meta span{padding:10px;background:#f4f8f9}.meta b{display:block;margin-top:4px}table{width:100%;border-collapse:collapse;margin:24px 0}th{background:var(--accent);color:white;text-align:left;padding:12px}td{padding:13px 12px;border-bottom:1px solid #dce5e8}th:last-child,td:last-child{text-align:right}.totals{width:min(390px,100%);margin-left:auto}.totals p{display:flex;justify-content:space-between;margin:0;padding:9px 0;border-bottom:1px solid #e1e8ea}.totals .grand{color:var(--accent);font-size:20px;font-weight:bold;border-bottom:3px double var(--accent)}.details{display:grid;grid-template-columns:1fr 1fr;gap:26px;margin-top:34px;padding-top:22px;border-top:1px solid #dce5e8}.details p{white-space:pre-line;line-height:1.6}.footer{text-align:center;margin-top:35px;color:#6b7d84;line-height:1.65}.actions{position:fixed;top:16px;right:16px}.actions button{border:0;border-radius:8px;background:var(--accent);color:white;padding:11px 16px;font-weight:bold;cursor:pointer}@media(max-width:650px){.sheet{padding:24px}.top,.grid,.details{grid-template-columns:1fr;display:grid}.title{text-align:left}}@media print{body{background:white}.sheet{width:100%;margin:0;box-shadow:none}.actions{display:none}}
    </style></head><body>${download?"":'<div class="actions"><button onclick="window.print()">Print / Save PDF</button></div>'}<main class="sheet">${headerBlock}<section class="top"><img class="logo" src="${esc(logoSrc)}" alt="Logo"><div class="title"><h1>${esc(field("title","current_title",invoice.direction==="purchase"?"BILL":"INVOICE"))}</h1><b>${esc(invoice.invoice_no)}</b></div></section><section class="grid"><div><p class="label">From</p><h2>${esc(field("seller_name","current_seller_name","StableCount"))}</h2><p class="address">${esc(field("seller_address","current_seller_address"))}\n${esc(field("seller_email","current_seller_email"))}\n${esc(field("seller_phone","current_seller_phone"))}</p></div><div><p class="label">Bill to</p><h2>${esc(invoice.client_name)}</h2><p class="address">${esc(invoice.client_address)}\n${esc(invoice.client_contact)}\n${esc(invoice.client_email)}\n${esc(invoice.client_phone)}</p><div class="meta"><span>Issue date<b>${esc(invoice.issue_date)}</b></span><span>Due date<b>${esc(invoice.due_date)}</b></span><span>Order<b>${esc(invoice.order_no||"—")}</b></span><span>Reference<b>${esc(invoice.reference||"—")}</b></span></div></div></section><table><thead><tr><th>Description</th><th>Qty</th><th>Unit price</th><th>Amount</th></tr></thead><tbody>${lineRows}</tbody></table><section class="totals"><p><span>Subtotal</span><b>${amount(invoice.subtotal,invoice.currency)}</b></p><p><span>Tax (${esc(invoice.tax_rate)}%)</span><b>${amount(invoice.tax_amount,invoice.currency)}</b></p><p><span>Discount</span><b>− ${amount(invoice.discount_amount,invoice.currency)}</b></p><p><span>Shipping</span><b>${amount(invoice.shipping_amount,invoice.currency)}</b></p><p class="grand"><span>Total</span><b>${amount(invoice.total,invoice.currency)}</b></p></section><section class="details"><div><p class="label">Payment details</p><p>${esc(field("bank_details","current_bank_details"))}\n${esc(invoice.receiving_bank)} · ${esc(invoice.bank_nickname)}\nAccount ending ${esc(invoice.account_last4)} · ${esc(invoice.bank_currency)}</p><p class="label">Tax registration</p><p>${esc(field("tax_registration","current_tax_registration","Not specified"))}</p></div><div><p class="label">Payment terms</p><p>${esc(field("payment_terms","current_payment_terms"))}</p><p class="label">Notes</p><p>${esc(invoice.notes||"—")}</p>${custom.map(entry=>`<p class="label">${esc(entry.label)}</p><p>${esc(entry.value)}</p>`).join("")}</div></section>${footerBlock}</main></body></html>`;
    return new Response(html,{headers:{"content-type":"text/html; charset=utf-8","content-disposition":`${download?"attachment":"inline"}; filename*=UTF-8''${encodeURIComponent(String(invoice.invoice_no)+".html")}`,"cache-control":"private, no-store","x-content-type-options":"nosniff"}});
  }catch(error){return Response.json({error:error instanceof Error?error.message:"Unable to generate invoice"},{status:400})}
}
