import { sql } from "drizzle-orm";
import { integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const clients = sqliteTable("clients", {
  id: integer("id").primaryKey({ autoIncrement: true }), name: text("name").notNull(), email: text("email").notNull(), phone: text("phone").notNull().default(""), address: text("address").notNull().default(""), country: text("country").notNull().default(""), website: text("website").notNull().default(""), directorCeoName: text("director_ceo_name").notNull().default(""), directorPhone: text("director_phone").notNull().default(""), directorEmail: text("director_email").notNull().default(""), inn: text("inn").notNull().default(""), kpp: text("kpp").notNull().default(""), ogrn: text("ogrn").notNull().default(""), contactPerson: text("contact_person").notNull().default(""), contactPosition: text("contact_position").notNull().default(""), contactEmail: text("contact_email").notNull().default(""), contactTel: text("contact_tel").notNull().default(""), contactMob: text("contact_mob").notNull().default(""), currency: text("currency").notNull().default("USD"), bankName: text("bank_name").notNull().default(""), bankReference: text("bank_reference").notNull().default(""), bankAccountNumber: text("bank_account_number").notNull().default(""), beneficiaryName: text("beneficiary_name").notNull().default(""), bankAddress: text("bank_address").notNull().default(""), swiftCode: text("swift_code").notNull().default(""), ifscCode: text("ifsc_code").notNull().default(""), commissionEarned: real("commission_earned").notNull().default(0), kind: text("kind", { enum: ["customer", "vendor", "both"] }).notNull().default("customer"), isActive: integer("is_active", { mode: "boolean" }).notNull().default(true), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const clientSupplierLinks = sqliteTable("client_supplier_links", {
  id: integer("id").primaryKey({ autoIncrement: true }), clientId: integer("client_id").notNull().references(() => clients.id), supplierId: integer("supplier_id").notNull().references(() => clients.id), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const bankAccounts = sqliteTable("bank_accounts", {
  id: integer("id").primaryKey({ autoIncrement: true }), nickname: text("nickname").notNull(), bankName: text("bank_name").notNull(), currency: text("currency").notNull().default("USD"), accountLast4: text("account_last4").notNull(), balance: real("balance").notNull().default(0), isDefault: integer("is_default", { mode: "boolean" }).notNull().default(false), isActive: integer("is_active", { mode: "boolean" }).notNull().default(true), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const orders = sqliteTable("orders", {
  id: integer("id").primaryKey({ autoIncrement: true }), orderNo: text("order_no").notNull().unique(), clientId: integer("client_id").notNull().references(() => clients.id), supplierId: integer("supplier_id").references(() => clients.id), description: text("description").notNull(), amount: real("amount").notNull().default(0), currency: text("currency").notNull().default("RUB"), purchasePrice: real("purchase_price").notNull().default(0), salePrice: real("sale_price").notNull().default(0), commissionPercent: real("commission_percent").notNull().default(0), purchaseCurrency: text("purchase_currency").notNull().default("RUB"), saleCurrency: text("sale_currency").notNull().default("RUB"), purchaseInvoiceDetails: text("purchase_invoice_details").notNull().default(""), salesInvoiceDetails: text("sales_invoice_details").notNull().default(""), status: text("status").notNull().default("Confirmed"), expectedDate: text("expected_date"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const shipments = sqliteTable("shipments", {
  id: integer("id").primaryKey({ autoIncrement: true }), shipmentNo: text("shipment_no").notNull().unique(), orderId: integer("order_id").notNull().references(() => orders.id), carrier: text("carrier").notNull().default(""), trackingNo: text("tracking_no").notNull().default(""), status: text("status").notNull().default("Preparing"), eta: text("eta"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const invoiceTemplates = sqliteTable("invoice_templates", {
  id: integer("id").primaryKey({ autoIncrement: true }), name: text("name").notNull(), direction: text("direction", { enum: ["sale", "purchase"] }).notNull().default("sale"), numberPrefix: text("number_prefix").notNull().default("INV"), title: text("title").notNull().default("INVOICE"), headerText: text("header_text").notNull().default(""), headerImageUrl: text("header_image_url").notNull().default(""), sellerName: text("seller_name").notNull(), sellerAddress: text("seller_address").notNull().default(""), sellerEmail: text("seller_email").notNull().default(""), sellerPhone: text("seller_phone").notNull().default(""), taxRegistration: text("tax_registration").notNull().default(""), bankDetails: text("bank_details").notNull().default(""), paymentTerms: text("payment_terms").notNull().default("Payment due within 30 days"), footer: text("footer").notNull().default("Thank you for your business"), footerImageUrl: text("footer_image_url").notNull().default(""), accentColor: text("accent_color").notNull().default("#176f8f"), customFieldsJson: text("custom_fields_json").notNull().default("[]"), isActive: integer("is_active", { mode: "boolean" }).notNull().default(true), createdBy: integer("created_by").notNull(), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const invoices = sqliteTable("invoices", {
  id: integer("id").primaryKey({ autoIncrement: true }), invoiceNo: text("invoice_no").notNull().unique(), clientId: integer("client_id").notNull().references(() => clients.id), bankAccountId: integer("bank_account_id").notNull().references(() => bankAccounts.id), orderId: integer("order_id").references(() => orders.id), templateId: integer("template_id").references(() => invoiceTemplates.id), direction: text("direction", { enum: ["sale", "purchase"] }).notNull().default("sale"), issueDate: text("issue_date").notNull(), dueDate: text("due_date").notNull(), currency: text("currency").notNull().default("USD"), subtotal: real("subtotal").notNull().default(0), taxRate: real("tax_rate").notNull().default(0), taxAmount: real("tax_amount").notNull().default(0), discountAmount: real("discount_amount").notNull().default(0), shippingAmount: real("shipping_amount").notNull().default(0), total: real("total").notNull().default(0), reference: text("reference").notNull().default(""), status: text("status").notNull().default("Sent"), notes: text("notes").notNull().default(""), templateSnapshot: text("template_snapshot").notNull().default("{}"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const invoiceItems = sqliteTable("invoice_items", {
  id: integer("id").primaryKey({ autoIncrement: true }), invoiceId: integer("invoice_id").notNull().references(() => invoices.id), description: text("description").notNull(), quantity: real("quantity").notNull().default(1), unitPrice: real("unit_price").notNull().default(0),
});
export const payments = sqliteTable("payments", {
  id: integer("id").primaryKey({ autoIncrement: true }), invoiceId: integer("invoice_id").references(() => invoices.id), clientId: integer("client_id").notNull().references(() => clients.id), bankAccountId: integer("bank_account_id").notNull().references(() => bankAccounts.id), direction: text("direction", { enum: ["in", "out"] }).notNull(), amount: real("amount").notNull(), paymentDate: text("payment_date").notNull(), reference: text("reference").notNull().default(""), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const journalEntries = sqliteTable("journal_entries", {
  id: integer("id").primaryKey({ autoIncrement: true }), entryDate: text("entry_date").notNull(), referenceType: text("reference_type").notNull(), referenceId: integer("reference_id").notNull(), memo: text("memo").notNull(), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const journalLines = sqliteTable("journal_lines", {
  id: integer("id").primaryKey({ autoIncrement: true }), entryId: integer("entry_id").notNull().references(() => journalEntries.id), accountCode: text("account_code").notNull(), accountName: text("account_name").notNull(), debit: real("debit").notNull().default(0), credit: real("credit").notNull().default(0), clientId: integer("client_id").references(() => clients.id),
});
export const appUsers = sqliteTable("app_users", {
  id: integer("id").primaryKey({ autoIncrement: true }), platformUserId: text("platform_user_id").unique(), email: text("email").notNull().unique(), displayName: text("display_name").notNull(), role: text("role", { enum: ["super_admin", "manager", "operator"] }).notNull().default("operator"), status: text("status", { enum: ["invited", "active", "disabled"] }).notNull().default("invited"), language: text("language").notNull().default("en"), defaultView: text("default_view").notNull().default("overview"), dateFormat: text("date_format").notNull().default("DD/MM/YYYY"), compactMode: integer("compact_mode", { mode: "boolean" }).notNull().default(false), reportingCurrency: text("reporting_currency").notNull().default("RUB"), timeFormat: text("time_format").notNull().default("24h"), timezone: text("timezone").notNull().default("UTC"), numberLocale: text("number_locale").notNull().default("en-US"), defaultInvoiceCurrency: text("default_invoice_currency").notNull().default("RUB"), defaultOrderCurrency: text("default_order_currency").notNull().default("RUB"), showTimestamps: integer("show_timestamps", { mode: "boolean" }).notNull().default(true), lastSeenAt: text("last_seen_at"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const userClientAssignments = sqliteTable("user_client_assignments", {
  id: integer("id").primaryKey({ autoIncrement: true }), userId: integer("user_id").notNull().references(() => appUsers.id), clientId: integer("client_id").notNull().references(() => clients.id), assignedBy: integer("assigned_by").notNull().references(() => appUsers.id), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const auditLog = sqliteTable("audit_log", {
  id: integer("id").primaryKey({ autoIncrement: true }), userId: integer("user_id").notNull().references(() => appUsers.id), action: text("action").notNull(), entityType: text("entity_type").notNull(), entityId: text("entity_id").notNull(), description: text("description").notNull(), detailsJson: text("details_json").notNull().default("{}"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const exchangeRates = sqliteTable("exchange_rates", {
  id: integer("id").primaryKey({ autoIncrement: true }), baseCurrency: text("base_currency").notNull(), quoteCurrency: text("quote_currency").notNull(), rate: real("rate").notNull(), effectiveDate: text("effective_date").notNull(), createdBy: integer("created_by").notNull().references(() => appUsers.id), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const documents = sqliteTable("documents", {
  id: integer("id").primaryKey({ autoIncrement: true }), clientId: integer("client_id").references(() => clients.id), orderId: integer("order_id").references(() => orders.id), fileName: text("file_name").notNull(), objectKey: text("object_key").notNull().unique(), contentType: text("content_type").notNull(), size: integer("size").notNull(), category: text("category").notNull().default("Other"), status: text("status").notNull().default("Uploaded"), createdBy: integer("created_by").notNull().references(() => appUsers.id), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});
